require('options')
require('plugins')
require('keymaps')
require('colorscheme')
require('lsp')
require('comp')

require('utils.treesitter')
require('utils.nvim-tree')
require('utils.bufferline')
require('utils.lualine')
require('utils.telescope')
require('utils.toggleterm')
require('utils.which-key')
require('utils.todo-comments')

